---
# Ansible Playbook for SAP S/4HANA Distributed HA installation

# Use include_role / include_tasks inside Ansible Task block, instead of using roles declaration or Task block with import_roles.
# This ensures Ansible Roles, and the tasks within, will be parsed in sequence instead of parsing at Playbook initialisation.

## Temporary IP and FS setup for ASCS and ERS
# in phase 1

#- name: Ansible Play for copying SAP NetWeaver ASCS installation media to host
#  hosts: nwas_ascs, nwas_ers
#  become: true
#  any_errors_fatal: true # https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html#aborting-a-play-on-all-hosts
#  max_fail_percentage: 0
#  tasks
#    - name: Transfer SAP NetWeaver ASCS installation media to host
#      delegate_to: "{{ sap_nwas_pas_ip }}"
#      remote_user: "root"
#      ansible.posix.synchronize:
#        src: "{{ item }}"
#        dest: "{{ sap_install_media_detect_source_directory }}"
#        mode: "push"
#        dest_port: 22
#        use_ssh_args: false
#        verify_host: false
#        private_key: "/tmp/hosts_rsa"
#        set_remote_user: false
#      loop: "{{ sap_nwas_ascs_install_media_files_list }}"




#### Begin SAP software installations ####


- name: Ansible Play for SAP NetWeaver Application Server installation - ABAP Central Services (ASCS) for HA
  hosts: nwas_ascs
  become: true
  any_errors_fatal: true # https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html#aborting-a-play-on-all-hosts
  max_fail_percentage: 0
  tasks:

    #- name: Execute Ansible Role sap_install_media_detect
    #  ansible.builtin.include_role:
    #    name: community.sap_install.sap_install_media_detect
    #  vars:
    #    sap_install_media_detect_swpm: true
    #    sap_install_media_detect_hostagent: true
    #    sap_install_media_detect_igs: true
    #    sap_install_media_detect_kernel: true
    #    sap_install_media_detect_webdisp: false

    # Install SAP NetWeaver ASCS via Ansible Role sap_swpm
    - name: Execute Ansible Role sap_swpm
      ansible.builtin.include_role:
        name: community.sap_install.sap_swpm
      vars:
        sap_swpm_templates_product_input: "{{ sap_swpm_templates_product_input_prefix }}_nwas_ascs_ha"
        sap_swpm_virtual_hostname: "{{ sap_swpm_ascs_instance_hostname }}"



- name: Ansible Play for SAP NetWeaver Application Server installation - Enqueue Replication Service (ERS) with Standalone Enqueue Server 2 (ENSA2)
  hosts: nwas_ers
  become: true
  any_errors_fatal: true # https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html#aborting-a-play-on-all-hosts
  max_fail_percentage: 0
  tasks:

    - name: Execute Ansible Role sap_install_media_detect
      ansible.builtin.include_role:
        name: community.sap_install.sap_install_media_detect
      vars:
        sap_install_media_detect_swpm: true
        sap_install_media_detect_hostagent: true
        sap_install_media_detect_igs: true
        sap_install_media_detect_kernel: true
        sap_install_media_detect_webdisp: false

    # Install SAP NetWeaver ERS via Ansible Role sap_swpm
    - name: Execute Ansible Role sap_swpm
      ansible.builtin.include_role:
        name: community.sap_install.sap_swpm
      vars:
        sap_swpm_templates_product_input: "{{ sap_swpm_templates_product_input_prefix }}_nwas_ers_ha"
        sap_swpm_ers_instance_nr: "{{ '%02d' | format(sap_swpm_ascs_instance_nr | int + 10) }}"
        sap_swpm_virtual_hostname: "{{ sap_swpm_ers_instance_hostname }}"



##################
# ASCS/ERS cluster
##################

- name: Ansible Play for SAP NetWeaver Application Server installation - High Availability using ABAP Central Services (ASCS) and Enqueue Replication Service (ERS) with Standalone Enqueue Server 2 (ENSA2)
  hosts: nwas_ascs, nwas_ers
  become: true
  any_errors_fatal: true # https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html#aborting-a-play-on-all-hosts
  max_fail_percentage: 0
  tasks:

    # Execute setup of SAP NetWeaver ASCS/ERS HA cluster
    # -- Linux Pacemaker cluster preparation
    # -- Linux Pacemaker basic cluster configuration, 2 nodes
    # -- SAP NetWeaver ASCS/ERS HA configuration, with a Virtual IP (VIP)
    # -- Fencing Agent/s setup for Infrastructure: fence_aws
    # -- Resource Agent/s setup for Infrastructure: aws-vpc-move-ip
    # -- Resource Agent/s setup for SAP: Filesystem, SAPInstance
    # -- SAP NetWeaver ASCS host:
    # ----> Filesystem for /sapmnt
    # ----> Filesystem for /usr/sap/trans
    # ----> Filesystem for /usr/sap/{{ sap_system_id }}/SYS
    # ----> Filesystem for /sapmnt
    # ----> Filesystem for /usr/sap/{{ sap_system_id }}/ASCS{{ sap_system_nwas_abap_ascs_instance_nr }}
    # ----> SAPInstance for /sapmnt/{{ sap_system_sid }}/profile/{{ sap_system_sid }}_ASCS{{ sap_system_nwas_abap_ascs_instance_nr }}
    # -- SAP NetWeaver ERS host:
    # ----> Filesystem for /usr/sap/{{ sap_system_id }}/ERS{{ sap_system_nwas_abap_ers_instance_nr }}
    # ----> SAPInstance for /sapmnt/{{ sap_system_sid }}/profile/{{ sap_system_sid }}_ERS{{ sap_system_nwas_abap_ers_instance_nr }}

    - name: Execute Ansible Role sap_ha_pacemaker_cluster
      ansible.builtin.include_role:
        name: community.sap_install.sap_ha_pacemaker_cluster
      vars:
        ha_cluster_cluster_name: clusternwasascs
        ha_cluster_hacluster_password: 'clusterpass'
        ha_cluster:
          node_name: "{{ ansible_hostname }}"
          pcs_address: "{{ ansible_default_ipv4.address }}"

        sap_ha_pacemaker_cluster_create_config_varfile: false

        sap_ha_pacemaker_cluster_host_type:
          - nwas_abap_ascs_ers

        sap_ha_pacemaker_cluster_vip_resource_group_name: vipnwasascs

        sap_ha_pacemaker_cluster_storage_definition: "{{ lookup('ansible.builtin.vars', 'sap_vm_provision_' + sap_vm_provision_iac_platform + '_host_specifications_dictionary')[sap_vm_provision_host_specification_plan][ansible_hostname].storage_definition | list }}"
        sap_ha_pacemaker_cluster_storage_nfs_filesytem_type: nfs4
        sap_ha_pacemaker_cluster_storage_nfs_mount_options: defaults,hard,acl
        sap_ha_pacemaker_cluster_storage_nfs_server: "{{ sap_storage_nfs_server | default('') }}"

        sap_ha_pacemaker_cluster_nwas_abap_sid: "{{ sap_system_sid | default('') }}"

        sap_ha_pacemaker_cluster_nwas_abap_ascs_instance_nr: "{{ sap_system_nwas_abap_ascs_instance_nr }}"
        sap_ha_pacemaker_cluster_nwas_abap_ers_instance_nr: "{{ sap_system_nwas_abap_ers_instance_nr }}"

        sap_ha_pacemaker_cluster_nwas_abap_ascs_sapinstance_instance_name: "{{ sap_system_sid }}_ASCS{{ sap_system_nwas_abap_ascs_instance_nr }}"
        sap_ha_pacemaker_cluster_nwas_abap_ascs_sapinstance_start_profile_string: "/sapmnt/{{ sap_system_sid }}/profile/{{ sap_system_sid }}_ASCS{{ sap_system_nwas_abap_ascs_instance_nr }}_{{ sap_swpm_ascs_instance_hostname }}"

        sap_ha_pacemaker_cluster_nwas_abap_ers_sapinstance_instance_name: "{{ sap_system_sid }}_ERS{{ sap_system_nwas_abap_ers_instance_nr }}"
        sap_ha_pacemaker_cluster_nwas_abap_ers_sapinstance_start_profile_string: "/sapmnt/{{ sap_system_sid }}/profile/{{ sap_system_sid }}_ERS{{ sap_system_nwas_abap_ers_instance_nr }}_{{ sap_swpm_ers_instance_hostname }}"


##########
# PAS
##########

- name: Ansible Play for SAP NetWeaver Application Server - Installation Export Database Load from the Primary Application Server (PAS)
  hosts: nwas_pas
  become: true
  any_errors_fatal: true # https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html#aborting-a-play-on-all-hosts
  max_fail_percentage: 0
  tasks:

    - name: Execute Ansible Role sap_install_media_detect
      ansible.builtin.include_role:
        name: community.sap_install.sap_install_media_detect
      vars:
        sap_install_media_detect_swpm: true
        sap_install_media_detect_hostagent: true
        sap_install_media_detect_igs: true
        sap_install_media_detect_kernel: true
        sap_install_media_detect_webdisp: false
        sap_install_media_detect_db_client: "saphana"
        sap_install_media_detect_export: "saps4hana"

    # Perform DB Load from SAP NetWeaver PAS host via Ansible Role sap_swpm
    - name: Execute Ansible Role sap_swpm
      ansible.builtin.include_role:
        name: community.sap_install.sap_swpm
      vars:
        sap_swpm_templates_product_input: "{{ sap_swpm_templates_product_input_prefix }}_nwas_pas_dbload_ha"
        sap_swpm_virtual_hostname: "{{ sap_swpm_pas_instance_hostname }}"



- name: Ansible Play for SAP NetWeaver Application Server - Primary Application Server (PAS)
  hosts: nwas_pas
  become: true
  any_errors_fatal: true # https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html#aborting-a-play-on-all-hosts
  max_fail_percentage: 0
  tasks:

    - name: Execute Ansible Role sap_install_media_detect
      ansible.builtin.include_role:
        name: community.sap_install.sap_install_media_detect
      vars:
        sap_install_media_detect_swpm: true
        sap_install_media_detect_hostagent: true
        sap_install_media_detect_igs: true
        sap_install_media_detect_kernel: true
        sap_install_media_detect_webdisp: false
        sap_install_media_detect_db_client: "saphana"
        sap_install_media_detect_export: "saps4hana" # Should not be necessary. Add to avoid unknown error from 'step SpecifyArchive' with error 'Parameter for download basket is empty' caused by no EXPORT files (aka. BACKUP1 'S4HANA2022CORE HANA DB Export 1')

    # Install SAP NetWeaver PAS via Ansible Role sap_swpm
    - name: Execute Ansible Role sap_swpm
      ansible.builtin.include_role:
        name: community.sap_install.sap_swpm
      vars:
        sap_swpm_templates_product_input: "{{ sap_swpm_templates_product_input_prefix }}_nwas_pas"



##########
# AAS
##########

- name: Ansible Play for SAP NetWeaver Application Server - Additional Application Servers (AAS)
  hosts: nwas_aas
  become: true
  any_errors_fatal: true # https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html#aborting-a-play-on-all-hosts
  max_fail_percentage: 0
  tasks:

    - name: Execute Ansible Role sap_install_media_detect
      ansible.builtin.include_role:
        name: community.sap_install.sap_install_media_detect
      vars:
        sap_install_media_detect_swpm: true
        sap_install_media_detect_hostagent: true
        sap_install_media_detect_igs: true
        sap_install_media_detect_kernel: true
        sap_install_media_detect_webdisp: false
        sap_install_media_detect_db_client: "saphana"

    # Install SAP NetWeaver AAS via Ansible Role sap_swpm
    - name: Execute Ansible Role sap_swpm
      ansible.builtin.include_role:
        name: community.sap_install.sap_swpm
      vars:
        sap_swpm_templates_product_input: "{{ sap_swpm_templates_product_input_prefix }}_nwas_aas"



    # - name: Execute Ansible Role sap_profile_update to update Profile for ICM HTTPS
    #   ansible.builtin.include_role:
    #     name: community.sap_operations.sap_profile_update
    #   vars:
    #     sap_update_profile_sid: "{{ sap_system_sid }}"
    #     sap_update_profile_instance_nr: "{{ sap_system_nwas_abap_pas_instance_nr }}"
    #     sap_update_profile_default_profile_params:
    #       - icm/server_port_1 = PROT=HTTPS,PORT=443$$,PROCTIMEOUT=600,TIMEOUT=3600
    #     sap_update_profile_instance_profile_params:
    #       - icm/server_port_1 = PROT=HTTPS,PORT=443$$,PROCTIMEOUT=600,TIMEOUT=3600

    # - name: Execute Ansible Role sap_control to restart SAP System/s for Profile update changes
    #   ansible.builtin.include_role:
    #     name: community.sap_operations.sap_control
    #   vars:
    #     sap_control_function: "restart_all_sap"



#### Post-install alterations for Infrastructure Platform ####

- name: "Ansible Play for Post-install alterations for Infrastructure Platform"
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Execute Ansible Role sap_vm_provision
      ansible.builtin.include_role:
        name: community.sap_infrastructure.sap_vm_provision
      vars:
        sap_vm_provision_iac_post_deployment: true
      when: sap_vm_provision_iac_type == "ansible"
