- name:  Ansible Play for SAP NetWeaver Application Server - Installation Export Database Load from the Primary Application Server (PAS)
  hosts: s4pas
  become: true
  any_errors_fatal: true
  max_fail_percentage: 0
  tasks:
    - name: ensure software mountpoint exists
      ansible.builtin.file:
         path: "{{ sap_swpm_software_path }}"
         state: directory
         mode: '0755'

    - name: Ensure SAP software directory is mounted
      ansible.posix.mount:
        src: "utility:{{ sap_swpm_software_path }}"
        path: "{{ sap_swpm_software_path }}"
        opts: rw
        boot: no
        fstype: nfs
        state: mounted

    - name: Execute Ansible Role sap_swpm
      ansible.builtin.include_role:
        name: community.sap_install.sap_swpm
      vars:
        sap_swpm_templates_product_input: "sap_s4hana_2021_distributed_nwas_pas"
        sap_swpm_virtual_hostname: "{{ sap_swpm_pas_instance_hostname }}"

    - name: Ensure SAP software directory is unmounted
      mount:
        path: "{{ sap_swpm_software_path }}"
        state: unmounted

