---
- name: "03-D HA Cluster deployment on a 2-node cluster"
  hosts: hanas
  become: true

  tasks:
    - name: Execute Cluster Setup Role
      ansible.builtin.include_role:
        name: community.sap_install.sap_ha_pacemaker_cluster
      vars:
        sap_ha_pacemaker_cluster_system_roles_collection: redhat.rhel_system_roles
        sap_ha_pacemaker_cluster_vip_client_interface: eth0
