- name: Step 3-C - Configure HANA System Replication
  hosts: hanas
  become: true

  tasks:
    - name: Configure System Replication
      include_role:
        name: community.sap_install.sap_ha_install_hana_hsr
