---
collections:
        - name: ansible.utils
        - name: community.sap_libs
          version: 1.1.0
        - name: community.sap_install
          version: 1.4.0
        - name: community.sap_operations
          version: 0.9.0
        - name: https://github.com/sap-linuxlab/community.sap_launchpad.git
          type: git
